version: "3"

services:
  auth-service:
    build: ./auth-service
    ports:
      - "8000:8000"
    networks:
      - micro-net

  content-service:
    build: ./content-service
    ports:
      - "8001:8001"
    networks:
      - micro-net

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - auth-service
      - content-service
    networks:
      - micro-net

networks:
  micro-net:
